### ISSUE TITLE
About the pipeline for generating multi-view dataset

### ISSUE THREAD

**Issue by Shelton0215** [icoz69/StyleAvatar3D#4]
I followed the pipeline you provided to generate a multi-view dataset, and below are the results from different viewpoints.Do you think these results are good for training the network?
![captrue](https://github.com/icoz69/StyleAvatar3D/assets/32185569/49adf2bb-4cb9-4095-89b8-694b78396fc1)

**Comment by icoz69** [comment]
which guidance do you use for ControlNet?

**Comment by Shelton0215** [comment]
> which guidance do you use for ControlNet?
Depth

**Comment by icoz69** [comment]
they look perfect overall, except the one at -30 degree, where the shoulder disappeared.  If this is occasional, it's fine as you can generate multiple images for each view. otherwise, you may also incorporate openpose guidance for further improvement.

**Comment by Shelton0215** [comment]
> they look perfect overall, except the one at -30 degree, where the shoulder disappeared. If this is occasional, it's fine as you can generate multiple images for each view. otherwise, you may also incorporate openpose guidance for further improvement.

If possible, could you please show me the multi-view data of a character that you generated? I would really appreciate it.

**Comment by icoz69** [comment]
<img width="1621" alt="image" src="https://github.com/icoz69/StyleAvatar3D/assets/22427667/d2991551-2deb-46bc-8ed5-eda3ae9d3758">

Here is one example. You may contact me through this email [ dr(dot)zhang(dot)chi@outlook.com ] for more discussions.

**Comment by songkey** [comment]
> <img alt="image" width="1621" src="https://user-images.githubusercontent.com/22427667/253229954-d2991551-2deb-46bc-8ed5-eda3ae9d3758.png">
> Here is one example. You may contact me through this email [ dr(dot)zhang(dot)[chi@outlook.com](mailto:chi@outlook.com) ] for more discussions.

Is this batch of sample data randomly shuffled? my understanding, an identity should have multiview generated images, like that:
![Dingtalk_20230713173152](https://github.com/icoz69/StyleAvatar3D/assets/7956388/f6a9f054-d131-4a84-8e26-4f08cd0ac347)
