### ISSUE TITLE
question about extracting depth map 

### ISSUE THREAD

**Issue by HL4214** [icoz69/StyleAvatar3D#6]
section4 of the paper introduce that using the Midas model to extract the depth map, I want to known why don't use the render library to generate depth map from avatars model, eg. pytorch3D, kaolin.

**Comment by icoz69** [comment]
hi, it is because ControlNet is trained with depth produced by Midas. Actually, Midas predicts uncalibrated disparity maps. Therefore, there's a gap between Midas's prediction and real depth.
